export const dashboardButtonData = [
	{
		index: 0,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-bars',
		buttonText: 'Notifications',
	},
	{
		index: 1,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'far dashboard-icon fa-bell',
		buttonText: 'Messages',
	},
	{
		index: 2,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-envelope-open',
		buttonText: 'Messages',
	},
	{
		index: 3,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-calendar-alt',
		buttonText: 'Events',
	},
	{
		index: 4,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-money-bill-alt',
		buttonText: 'Gigs',
	},
	{
		index: 5,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-plus-square',
		buttonText: 'Following',
	},
	{
		index: 6,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-users',
		buttonText: 'Friends',
	},
	{
		index: 7,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-search',
		buttonText: 'Discover',
	},
	{
		index: 8,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-sign-out-alt',
		buttonText: 'Log Out',
	},
	{
		index: 9,
		path: null,
		classNames: 'dashboard-btn',
		icon: 'fas dashboard-icon fa-cogs',
		buttonText: 'Settings',
	},
];
